type: dnf
install:
  packages:
    # Desktop Apps
    - alacritty
    - blueman
    - firewall-config
    - gnome-disk-utility
    - gnome-keyring
    - gnuplot
    - imv
    - kitty
    - kitty-terminfo
    - mate-polkit
    - network-manager-applet
    - pass
    - pavucontrol
    - remmina
    - swappy
    - system-config-printer
    - thunar
    - thunar-archive-plugin
    - thunar-volman
    - nautilus
    - udiskie
    - vlc
    - wayvnc
    - xarchiver
    - zathura
    - zathura-pdf-poppler
    # Developer
    - dbus-x11
    - git-credential-libsecret
    - git-lfs
    - pipx
    - uv
    - direnv
    - zoxide
    # Fonts Themes
    - fontawesome-fonts-all
    - gnome-icon-theme
    - gnome-themes-extra
    - google-noto-emoji-fonts
    - google-noto-fonts-common
    - google-noto-sans-fonts
    - google-roboto-fonts
    - overpass-fonts
    - overpass-mono-fonts
    # Intel Support
    - linux-firmware
    - mesa-dri-drivers
    - mesa-libGLU
    - mesa-vulkan-drivers
    - vulkan-tools
    - vulkan-validation-layers
    # Login Manager
    - sddm
    - sddm-themes
    # Media Hardware
    - alsa-sof-firmware
    - bluez
    - bluez-tools
    - brightnessctl
    - gvfs
    - gvfs-mtp
    - pamixer
    - pipewire
    - pipewire-alsa
    - pipewire-jack-audio-connection-kit
    - pipewire-pulseaudio
    - wireplumber
    # System Core
    - acpi
    - age
    - aria2
    - bolt
    - cmake
    - cpio
    - distrobox
    - fish
    - fprintd-pam
    - g++
    - gcc
    - gcc-c++
    - gh
    - lame
    - libadwaita
    - make
    - meson
    - neovim
    - NetworkManager-openconnect
    - NetworkManager-openvpn
    - NetworkManager-tui
    - p7zip
    - pandoc
    - podman-compose
    - podman-tui
    - podmansh
    - python3-cairo
    - python3-pip
    - ripgrep
    - sox
    - tuned
    - tuned-switcher
    - tuned-utils
    - unrar-free
    - wmctrl
    - ydotool
    - yt-dlp
    # Sytem Portals
    # - better-settings
    - dbus-daemon
    - dbus-tools
    - gsettings-desktop-schemas
    - lxpolkit
    - lxqt-policykit
    - polkit
    - polkit-kde
    - xdg-desktop-portal
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-wlr
    - xdg-user-dirs
    # Wayland Environment
    - azote
    #- grimshot
    - grim
    - kanshi
    - light
    - mako
    - playerctl
    - rofi-wayland
    - rofimoji
    - slurp
    - waybar
    - wf-recorder
    - wl-clipboard
    - wlr-randr
    - wshowkeys
    - wtype
    - xorg-x11-server-Xwayland
    # Local AI functionality
    - ollama
    - ramalama
    # added from ax-shell instructions
    - tesseract
    - webp-pixbuf-loader 
    - python3-gobject 
    - python3-numpy 
    - python3-pillow 
    - python3-psutil 
    - python3-ramalama
    - python3-requests 
    - python3-toml 
    - python3-watchdog 
    - python3-pywayland 
    - python3-ijson 
    - python3-setproctitle
    # networking
    - caddy
    - tailscale
    - cockpit
    - cockpit-machines
    - cockpit-networkmanager
    - cockpit-podman
    - cockpit-selinux
    - cockpit-storaged
    - cockpit-system
