---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: zen
description: Fedora Atomic spin for Asus Zenbook Duo
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Base configurations
  - from-file: base/desktop-apps.yml
  - from-file: base/fonts-themes.yml
  - from-file: base/intel-support.yml
  - from-file: base/login-manager.yml
  - from-file: base/media-hardware.yml
  - from-file: base/system-core.yml
  - from-file: base/sytem-portals.yml
  - from-file: base/wayland-environment.yml
  # COPR repositories
  - from-file: copr/all-packages.yml
  - from-file: copr/zenrpm.yml
  # YUM configurations
  - from-file: yum/developer.yml

  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - virtualbox-guest-additions
      - toolbox
      - nvtop

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - tailscaled.service
 #       - ollama-boot.service
      disabled:
        - rpm-ostree-countme.timer
        #user:
        # enabled:
        #- ollama.service
        #- ollama-web.service
        
  - type: script
    scripts:
      - settheming.sh
      - post-install.sh

  - type: chezmoi
    repository: "https://github.com/mecattaf/dots-zen"
    run-every: '1d'
    wait-after-boot: '5m'
    disable-init: false
    disable-update: false

  - type: justfiles
    validate: false
    include:
      - whisper.just

  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.google.Chrome
        - app.zen_browser.zen
        - it.mijorus.gearlever
        - org.desmume.DeSmuME
        - io.mgba.mGBA
        - com.hunterwittenborn.Celeste
        - it.mijorus.collector
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - io.bassi.Amberol
          #- org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          #- org.freedesktop.Platform.GStreamer.gstreamer-vaapi

  - type: signing
