---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: duo
description: Fedora Atomic spin for dual-screen laptops like Asus Zenbook Duo
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - from-file: base.yml
  - from-file: copr.yml
  - from-file: quickshell.yml

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - virtualbox-guest-additions
        - toolbox
        - nvtop

  - type: files
    files:
      - source: system
        destination: /

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - tailscaled.service
      disabled: []

  - type: script
    snippets:
      - "sed -i 's/Inherits=Catppuccin-Noir-Standard-Green-Dark/Inherits=Catppuccin-SE/' /usr/share/icons/default/index.theme"

  - type: chezmoi
    repository: "https://github.com/mecattaf/dotfiles"
    run-every: '1d'
    wait-after-boot: '5m'
    disable-init: false
    disable-update: false

  - type: brew
    nofile-limits: true  # default: false
    brew-analytics: false # default: true

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        install:
          - com.google.Chrome
          - it.mijorus.gearlever
          - org.desmume.DeSmuME
          - io.mgba.mGBA
          - com.hunterwittenborn.Celeste
          - it.mijorus.collector
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - org.gnome.Lollypop
          - org.mozilla.firefox
          # - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          # - org.freedesktop.Platform.GStreamer.gstreamer-vaapi

  - type: signing
