---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: zen
description: Fedora Atomic spin for Asus Zenbook Duo
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - from-file: base.yml
  - from-file: copr.yml

  - type: dnf
    packages:
      remove:
        - firefox
        - firefox-langpacks
        - virtualbox-guest-additions
        - toolbox
        - nvtop

  - type: files
    files:
      - source: system
        destination: /

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - Iosevka
        - NerdFontsSymbolsOnly

  - type: systemd
    system:
      enabled:
        - sddm-boot.service
      disabled:
        #- rpm-ostree-countme.timer
        
  - type: script
    scripts:
      - settheming.sh
      #- post-install.sh

  - type: chezmoi
    repository: "https://github.com/mecattaf/dots-zen"
    run-every: '1d'
    wait-after-boot: '5m'
    disable-init: false
    disable-update: false

  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.google.Chrome
        - it.mijorus.gearlever
        - org.desmume.DeSmuME
        - io.mgba.mGBA
        - com.hunterwittenborn.Celeste
        - it.mijorus.collector
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - io.bassi.Amberol
          #- org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          #- org.freedesktop.Platform.GStreamer.gstreamer-vaapi

  - type: signing
