---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: duo
description: Fedora Atomic spin for dual-screen laptops like Asus Zenbook Duo
base-image: ghcr.io/ublue-os/base-main
image-version: 42

modules:
  - from-file: base.yml
  - from-file: copr.yml
  - from-file: quickshell.yml

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - virtualbox-guest-additions
        - toolbox
        - nvtop

#  - type: kargs
#    kargs:
#      - amd_iommu=off
#      - amdgpu.gttsize=131072
#      - ttm.pages_limit=33554432

  - type: files
    files:
      - source: system
        destination: /

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro
        - Iosevka
        - NerdFontsSymbolsOnly
      url-fonts:
        - name: Apple-SF
          url: https://github.com/mecattaf/San-Francisco-family/releases/download/v1.0/apple-sf-nerd-patched.zip
        - name: SFMono-Nerd-Font-Ligaturized
          url: https://github.com/mecattaf/San-Francisco-family/releases/download/v1.0/SFMono-Liga.zip


  - type: systemd
    system:
      enabled:
        - sddm-boot.service
        - enable-linger.service
        - autologin.service
        - tailscaled.service
      disabled: []

  - type: chezmoi
    repository: "https://github.com/mecattaf/dotfiles"
    run-every: '1d'
    wait-after-boot: '5m'
    disable-init: false
    disable-update: false

  - type: brew
    nofile-limits: true  # default: false
    brew-analytics: false # default: true

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        install:
          - com.google.Chrome
          - it.mijorus.gearlever
          - com.hunterwittenborn.Celeste
          - it.mijorus.collector
          - com.obsproject.Studio
          - com.obsproject.Studio.Plugin.OBSVkCapture
          - org.gnome.Lollypop
          - org.mozilla.firefox
          # - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
          # - org.freedesktop.Platform.GStreamer.gstreamer-vaapi

  - type: signing
